[project]
name = "chimera"
version = "0.2"
description = ""
readme = "README.rst"
authors = [
    { name = "Paulo Henrique Silva", email = "ph.silva@gmail.com" },
    { name = "William Schoenell", email = "wschoenell@gmail.com" },
]
requires-python = ">=3.12"
dependencies = [
    "redis[hiredis]>=5.0.8",
    "pyyaml>=6.0.2",
    "python-dateutil>=2.9.0.post0",
    "pyephem>=9.99",
    "numpy>=2.1.1",
    "astropy>=6.1.3",
    "suds>=1.2.0",
    "redislite>=6.2.912183",
    # "RO",
    # "SQLAlchemy",
    "rich>=13.9.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "black>=25.1.0",
    "furo>=2024.8.6",
    "pre-commit>=4.1.0",
    "pytest>=8.3.3",
    "pytest-cov>=6.0.0",
    "ruff>=0.9.4",
    "sphinx>=8.1.3",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--import-mode=importlib"
