[project]
name = "chimera"
version = "0.2"
description = "Chimera - Observatory Automation System"
readme = "README.rst"
license = "GPL-2.0-or-later"
authors = [
    { name = "Paulo Henrique Silva", email = "ph.silva@gmail.com" },
    { name = "William Schoenell", email = "wschoenell@gmail.com" },
]
urls = { "homepage" = "https://chimera.readthedocs.org", "source" = "https://github.com/astroufsc/chimera" }

classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Astronomy",
]

# TODO: Add scripts
# "src/scripts/chimera",
# "src/scripts/chimera-cam",
# "src/scripts/chimera-admin",
# "src/scripts/chimera-filter",
# "src/scripts/chimera-tel",
# "src/scripts/chimera-dome",
# "src/scripts/chimera-focus",
# "src/scripts/chimera-console",
# "src/scripts/chimera-sched",
# "src/scripts/chimera-weather",
# "src/scripts/chimera-seeing",

requires-python = ">=3.12"
dependencies = [
    "redis[hiredis]>=5.0.8",
    "pyyaml>=6.0.2",
    "python-dateutil>=2.9.0.post0",
    "pyephem>=9.99",
    "numpy>=2.1.1",
    "astropy>=6.1.3",
    "suds>=1.2.0",
    "redislite>=6.2.912183",
    "rich>=13.9.4",
    "sqlalchemy==1.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "black>=25.1.0",
    "pre-commit>=4.1.0",
    "pytest>=8.3.3",
    "pytest-cov>=6.0.0",
    "ruff>=0.9.4",
]

[dependency-groups]
docs = ["furo>=2024.8.6", "sphinx>=8.1.3"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--import-mode=importlib"
