
CHIMERA_ROOT=$HOME/chimera/chimera-stable
CHIMERA_PYTHON_PATH=$CHIMERA_ROOT/src
CHIMERA_BIN=$CHIMERA_ROOT/src/scripts

PYRO_PATH=$HOME/Pyro-3.6

export PYTHONPATH=$CHIMERA_PYTHON_PATH:$PYRO_PATH
export PATH=$CHIMERA_BIN:$PATH

