#!/bin/bash
#
#	/etc/rc.d/init.d/sbigcam
#
# Loads camera modules.
#
# chkconfig: 3 40 62
# description: Loads SBIG proprietary modules for ST-7 cameras.
# processname: sbigcam 

# Source function library.
. /etc/rc.d/init.d/functions

. /etc/sysconfig/uts

test -x $UTS_BIN/sbig_load_usb || exit 0
test -x $UTS_BIN/sbig_unload_usb || exit 0
test -x $UTS_BIN/sbig_load_lpt || exit 0
test -x $UTS_BIN/sbig_unload_lpt || exit 0

RETVAL=0

#
#	See how we were called.
#
case "$1" in
  start)
	# Check if modules are already loaded
	if [ ! -f /var/lock/subsys/sbigcam ]; then
	    echo 'Loading SBIG proprietary ST-7E camera modules:'
	    $UTS_BIN/sbig_load_usb
	    $UTS_BIN/sbig_load_lpt
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/sbigcam
	    echo
	fi
	;;
  stop)
	echo 'Unloading SBIG proprietary ST-7E camera modules:'
	$UTS_BIN/sbig_unload_usb
	$UTS_BIN/sbig_unload_lpt 
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/sbigcam
	echo
	;;
  reload|restart)
	$0 stop
	$0 start
	RETVAL=$?
	;;
  *)
	echo "Usage: /etc/rc.d/init.d/spmd {start|stop|restart|reload}"
	exit 1
esac

exit $RETVAL
