#!/bin/bash
#
#	/etc/rc.d/init.d/secd
#
# Starts the Socket Secretary daemon
#
# chkconfig: 3 41 61
# description: Run socket secretaries for each instrument.

# Source function library.
. /etc/rc.d/init.d/functions

. /etc/sysconfig/uts

test -x $UTS_BIN/sec || exit 0

RETVAL=0

#
#	See how we were called.
#
case "$1" in
  start)
	    echo -n 'Starting Socket Secretary daemons... '
	    #daemon $UTS_BIN/runsecs.sh
	    for INST in `ls -1 $UTS_SEC/*.conf`; do
	          daemon $UTS_BIN/sec -d $INST;
            done
	    touch /var/lock/subsys/secd
	    echo
	;;
  stop)
	echo -n 'Stopping Socket Secretary daemon: '
	killproc sec
	rm -f /var/lock/subsys/secd
	echo
	;;
  reload|restart)
	$0 stop
	$0 start
	RETVAL=$?
	;;
  status)
	status $UTS_BIN/sec
	RETVAL=$?
	;;
  *)
	echo "Usage: /etc/rc.d/init.d/secd {start|stop|restart|reload|status}"
	exit 1
esac

exit $RETVAL
