# python version 1.0						DO NOT EDIT
#
# Generated by smidump version 0.4.8:
#
#   smidump -f python CHIMERA-MIB

FILENAME = "CHIMERA-MIB.txt"

MIB = {
    "moduleName" : "CHIMERA-MIB",

    "CHIMERA-MIB" : {
        "nodetype" : "module",
        "language" : "SMIv1",
    },

    "imports" : (
        {"module" : "RFC1155-SMI", "name" : "experimental"},
        {"module" : "RFC-1212", "name" : "OBJECT-TYPE"},
        {"module" : "RFC1213-MIB", "name" : "DisplayString"},
        {"module" : "", "name" : "Float"},
        {"module" : "SNMPv2-TC", "name" : "TruthValue"},
    ),

    "nodes" : {
        "chimera" : {
            "nodetype" : "node",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53",
        }, # node
        "telescopeGroup" : {
            "nodetype" : "node",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.1",
        }, # node
        "telescopeName" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The name of the telescope under chimera's control.""",
        }, # scalar
        "telescopeModel" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.1.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The model of the telescope under chimera's control.""",
        }, # scalar
        "telescopeDevice" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.1.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The device the telescope uses to communicate with chimera.""",
        }, # scalar
        "telescopeOptics" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.1.4",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The elescope's optics type.""",
        }, # scalar
        "telescopeAperture" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.1.5",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """The telescope's aperture size in millimeters.""",
        }, # scalar
        "telescopeMount" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.1.6",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The telescope's mount type.""",
        }, # scalar
        "telescopeFocalLength" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.1.7",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The telescope's focal length.""",
        }, # scalar
        "cameraGroup" : {
            "nodetype" : "node",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.2",
        }, # node
        "cameraDevice" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.2.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The device connecting the camera to the computer.""",
        }, # scalar
        "cameraCCD" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.2.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The detector model inside the camera.""",
        }, # scalar
        "cameraTempDelta" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.2.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The temperature delta permissible for the detector.""",
        }, # scalar
        "cameraCCDSaturationLevel" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.2.4",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The detector saturation level.""",
        }, # scalar
        "cameraModel" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.2.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The camera's model.""",
        }, # scalar
        "cameraCCDModel" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.2.6",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The camera's CCD model.""",
        }, # scalar
        "cameraTelescopeFocalLength" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.2.7",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The camera's optics focal length.""",
        }, # scalar
        "domeGroup" : {
            "nodetype" : "node",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.3",
        }, # node
        "domeDevice" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.3.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The dome's device.""",
        }, # scalar
        "domeTelescope" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.3.2",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The telescope inside this dome.""",
        }, # scalar
        "domeMode" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.3.3",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The dome's current mode: tracking - not tracking.""",
        }, # scalar
        "domeModel" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.3.4",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The dome's manufacturer model.""",
        }, # scalar
        "domeStyle" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.3.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The dome style.""",
        }, # scalar
        "domeParkPosition" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.3.6",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """The The dome's parking position.""",
        }, # scalar
        "domeParkOnShutdown" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.3.7",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Park the dome at shutdown time.""",
        }, # scalar
        "domeCloseOnShutdown" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.3.8",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Close the dome shutter at shutdown time.""",
        }, # scalar
        "domeAzResolution" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.3.9",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Azimuth resolution of the dome's position.""",
        }, # scalar
        "domeSlewTimeout" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.3.10",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Dome slew command timeout.""",
        }, # scalar
        "domeAbortTimeout" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.3.11",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Dome abort command timeout.""",
        }, # scalar
        "domeInitTimeout" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.3.12",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Dome initalization command timeout.""",
        }, # scalar
        "domeOpenTimeout" : {
            "nodetype" : "scalar",
            "moduleName" : "CHIMERA-MIB",
            "oid" : "1.3.6.1.3.53.3.13",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "RFC1213-MIB",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "256"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "256"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Dome open command timeout.""",
        }, # scalar
    }, # nodes

}
