# PySNMP SMI module. Autogenerated from smidump -f python FLOAT-TC-MIB
# by libsmi2pysnmp-0.1.3 at Wed Jul  2 17:05:48 2014,
# Python version sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( Bits, Integer32, ModuleIdentity, MibIdentifier, TimeTicks, mib_2, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "ModuleIdentity", "MibIdentifier", "TimeTicks", "mib-2")
( TextualConvention, ) = mibBuilder.importSymbols("SNMPv2-TC", "TextualConvention")

# Types

class Float128TC(OctetString):
    subtypeSpec = OctetString.subtypeSpec+ValueSizeConstraint(16,16)
    fixedLength = 16
    
class Float32TC(OctetString):
    subtypeSpec = OctetString.subtypeSpec+ValueSizeConstraint(4,4)
    fixedLength = 4
    
class Float64TC(OctetString):
    subtypeSpec = OctetString.subtypeSpec+ValueSizeConstraint(8,8)
    fixedLength = 8
    

# Objects

floatTcMIB = ModuleIdentity((1, 3, 6, 1, 2, 1, 201)).setRevisions(("2011-07-27 00:00",))
if mibBuilder.loadTexts: floatTcMIB.setOrganization("IETF OPSAWG Working Group")
if mibBuilder.loadTexts: floatTcMIB.setContactInfo("WG Email: opsawg@ietf.org\n\nEditor: Randy Presuhn\nrandy_presuhn@mindspring.com")
if mibBuilder.loadTexts: floatTcMIB.setDescription("Textual conventions for the representation\nof floating-point numbers.\n\n\n\nCopyright (c) 2011 IETF Trust and the persons\nidentified as authors of the code.  All rights\nreserved.\n\nRedistribution and use in source and binary forms,\nwith or without modification, is permitted pursuant\nto, and subject to the license terms contained in,\nthe Simplified BSD License set forth in Section\n4.c of the IETF Trust's Legal Provisions Relating\nto IETF Documents\n(http://trustee.ietf.org/license-info).\n\nThis version of this MIB module is part of RFC 6340;\nsee the RFC itself for full legal notices.")

# Augmentions

# Exports

# Module identity
mibBuilder.exportSymbols("FLOAT-TC-MIB", PYSNMP_MODULE_ID=floatTcMIB)

# Types
mibBuilder.exportSymbols("FLOAT-TC-MIB", Float128TC=Float128TC, Float32TC=Float32TC, Float64TC=Float64TC)

# Objects
mibBuilder.exportSymbols("FLOAT-TC-MIB", floatTcMIB=floatTcMIB)

