class Transport:
    def __init__(self, url: str):
        self.url = url

    def ping(self) -> bool: ...

    def bind(self) -> None: ...

    def connect(self) -> None: ...

    def close(self) -> None: ...

    def send(self, data: bytes) -> None: ...

    def recv(self) -> bytes: ...

    def fd(self) -> int: ...
